Add items to Subprojects section
ros-realtime/community pull request #15
Opened 2021-03-11 10:04 UTC by carlossvg

# Working Group Modification Pull Request

# Add Project

This MR adds some projects to the subprojects section.

2021-03-11 15:22 UTC, christophebedard requested changes

2021-03-11 15:22 UTC, christophebedard commented on README.md
> +
removing this empty line will fix the weird vertical spacing: https://github.com/ros-realtime/community/blob/add-subprojects/README.md

2021-03-11 15:27 UTC, christophebedard commented on README.md
> +  - https://github.com/hsgwa/ros2_timer_latency_measurement
a bit nitpicky, but the two items above don't have a `- Repositories` line before the repo link (unlike all the other items).

2021-03-11 16:02 UTC, carlossvg commented on README.md
> +
Fixed

2021-03-11 16:02 UTC, carlossvg commented on README.md
> +  - https://github.com/hsgwa/ros2_timer_latency_measurement
Fixed. Thanks for the review!

2021-03-11 16:05 UTC, christophebedard approved these changes
I can't think of anything that's missing. In any case, we can always add more projects later on!

2021-03-11 16:08 UTC, christophebedard commented
oh wait what about https://github.com/osrf/osrf_testing_tools_cpp?

2021-03-11 16:54 UTC, carlossvg commented
> oh wait what about https://github.com/osrf/osrf_testing_tools_cpp?

Good catch! I think we should add these too:
- https://gitlab.com/ApexAI/apex_containers 
- https://gitlab.com/ApexAI/apex_test_tools

2021-03-11 19:08 UTC, christophebedard commented
looks good!

2021-03-11 19:39 UTC, razr commented
there are also
https://github.com/ros2/buildfarm_perf_tests
https://github.com/ros2/performance_test

**Performance evaluation** - probably **Performance measurements** is a better name?

2021-03-12 08:01 UTC, carlossvg commented
> there are also
> https://github.com/ros2/buildfarm_perf_tests
> https://github.com/ros2/performance_test
> 
> **Performance evaluation** - probably **Performance measurements** is a better name?

Updated

2021-03-12 08:43 UTC, carlossvg commented
I added https://github.com/ros-controls/realtime_tools/tree/foxy-devel/include/realtime_tools

2021-03-12 10:47 UTC, merged